version: 2

sources:
  - name: jaffle_shop
    database: raw

    tables:
      - name: orders
        freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
        loaded_at_field: _etl_loaded_at